version: "3"
services:
  marco_bot_dev:
    container_name: marco_bot_dev
    restart: always
    build: .
    ports:
      - "4000:4000"
    volumes:
      - $HOME/Marco/MarcoBot:/usr/src/api
    network_mode: "env-net"
    external_links:
      - "api:api"
      - "recommendation_api:recommendation_api"
networks:
  default:
    external:
      name: env-net
