version: "3"
services:
  marco_bot:
    container_name: marco_bot
    restart: always
    build: .
    ports:
      - "4005:4005"
    volumes:
      - /etc/api/MarcoBot:/usr/src/api
    network_mode: "env-net"
    external_links:
      - "api:api"
      - "recommendation_api:recommendation_api"
networks:
  default:
    external:
      name: env-net
