version: "3"
services:
  marco_bot:
    container_name: marco_bot
    restart: always
    build: .
    volumes:
          - $HOME/Marco/MarcoBot:/usr/src/api
    ports:
      - "4000:4000"
    volumes:
      - /etc/api/MarcoBotDev:/usr/src/api
    network_mode: "env-net"
    external_links:
      - "api:api"
      - "recommandation_api:recommandation_api"
networks:
  default:
    external:
      name: env-net
