const arrayOfAnecdote = (locale) => {

  return locale === 'fr' ? [
    "La tour Eiffel devrait s'appeler la tour Nouguier et la tour Koechlin. \nEn effet, Koechlin et Nouguier, deux ingénieurs des ateliers de Gustave Eiffel, ont eu l’idée de la Dame de fer pour briller lors de l’exposition universelle de 1889, Eiffel étant initialement totalement désintéressé du projet. \nIl a eu la bonne idée d'acheter le brevet pour présenter la fameuse construction qui a finalement reçu son nom! ",
    "Il n'y a qu'un seul panneau stop dans toute la ville. \nLe gagnant est le quai St Exupéry. Outre cet endroit, la règle de la priorité à droite s’applique au reste de la ville.",
    "Tu devez payer 200 000 € pour être chauffeur de taxi à Paris. \n\nSi tu as déjà été à Paris, tu as peut-être remarqué que les taxis sont presque impossibles à trouver. Le samedi soir, il est très fréquent de voir des dizaines de personnes sur le trottoir attendre ou se battre pour un taxi.",
    "Paradoxalement, le Pont Neuf est le plus ancien pont de la capitale. \n\nAu début du 17ème siècle, il a été baptisé ça car il était très innovant d'avoir un vrai trottoir contrairement aux anciens ponts de Paris, pour éviter ainsi aux piétons de marcher dans des excréments de chevaux.",
    "Le célèbre Pont des Amours n'existe plus. En fait, le pont est toujours là, mais tous les cadenas ont été enlevés pour des raisons de sécurité. \nEn effet, avec environ 1 million de cadenas, représentant un poids de 45 tonnes, ils ont sérieusement endommagé la structure du pont. \nLa ville de Paris a été vivement critiquée pour avoir pris la décision de supprimer les cadenas emblématiques, considérés par la plupart des parisiens (et des touristes!) comme un patrimoine culturel et comme l'un des principaux symboles de la ville. ",
    "Le terme \"poulet\" pour désigner un policier est né à Paris! Après l’incendie des locaux de la police, la préfecture de police s’est installée sur l’île de la Cité, dans des locaux mis à disposition par Jules Ferry. Ces locaux ayant été construits sur l'ancien site où se tenait le marché aux volailles de la capitale, il ne fallut pas longtemps pour appeler les policiers ... \"poulets\"!",
    "La Tour Eiffel n'est pas le monument le plus visité de Paris.\nEn 2014, la Tour Eiffel n'était que le quatrième site le plus visité de la capitale française. C'est la cathédrale Notre-Dame de Paris qui arrive en première position.",
    "La cloche principale de la cathédrale Notre-Dame pèse 13 tonnes. Ou plus que le poids de 3 éléphants. La partie intérieure de la cloche pèse à elle seule 500 kg. \nLa cloche sonne pour les grandes fêtes catholiques telles que Noël, Pâques, la Pentecôte, etc., ou pour d'autres événements importants tels que la mort du pape Jean-Paul II et l'élection de son successeur Benoît XVI. \nOh, et la plus grosse cloche a un nom: Emmanuel.",
    "Les stations de métro fantômes se cachent sous le sol parisien. \nEt pas seulement une ... 14 stations de métro fantômes sont cachées dans le sous-sol de la capitale. La plupart d'entre elles ont été fermés au début de la seconde guerre mondiale, alors qu'une grande partie du personnel avait été mobilisée pour la guerre. \nCertaines d'entre elles ont ensuite été rouvertes temporairement, puis définitivement abandonnées, trop proches des autres stations. C’est le cas, par exemple, de la gare Saint-Martin, située à 100 mètres de Strasbourg-St Denis. \nC'est l'une des plus grandes ressources abandonnées de la capitale, régulièrement visitée par des explorateurs urbains...",
    "La Place de la Concorde est l'un des plus grands cadrans solaires au monde. \n La plupart des Parisiens eux-mêmes ne le savent pas, mais la Place de la Concorde est un cadran géant. L’obélisque (le monument principal de la place, colonne égyptienne de 23 mètres de haut) peut lire l’heure approximative en fonction de son ombre, en fonction de la position du soleil.\nSi tu fais attention en te promenant sur la place de la Concorde, tu remarqueras même des marqueurs de l'heure en chiffres romains sur le trottoir.",
] :[
    "The Eiffel Tower should be called the Nouguier and Koechlin Tower. \nIn fact, Koechlin and Nouguier, two engineers of the workshops of Gustave Eiffel had the idea of ​​the Iron Lady to shine during the universal exhibition of 1889, Eiffel was initially completely disinterested of the project. \nHe had the good idea to buy the patent to present himself the famous construction which was finally given his name! ",
    "There is only one stop sign in the whole city. \nThe lucky winner is quai St Exupéry. Apart from this place, the right-of-priority rule applies to the rest of the city.",
    "You have to pay € 200,000 to be a taxi driver in Paris. \nIf you've been to Paris before, you may have noticed that taxis are almost impossible to find. On Saturday nights, it is very common to see dozens of people on the sidewalk waiting for or fighting for a taxi. \nAnd it comes from the \"simple\" fact that taxi drivers have to pay the small sum of ... 200 000 € to get a license. We understand a little better why they are not a fan of services like Uber!",
    "Paradoxically, the Pont Neuf is the oldest bridge in the capital. \nIn the early 17th, it was named as it since it was very new to have a real sidewalk contrary to the old bridges in Paris, thus avoiding pedestrians from walking in horse dung.",
    "The famous Pont des Amours no longer exists. In fact, the bridge is still there, but all padlocks have been removed for security reasons. \nIndeed, with about 1 million padlocks, representing a weight of 45 tons, they began to seriously damage the structure of the bridge. \nThe City of Paris was strongly criticized for taking the decision to remove emblematic padlocks, considered by most Parisians (and tourists!) s a cultural heritage and as one of the main symbols of the city.",
    "The term \"chicken\" to designate a policeman was born in Paris! After the police buildings caught fire, the Prefecture of Police settled on the L’’île de la Cité, in premises made available by Jules Ferry. These premises having been built on the former site where was held the poultry market of the capital, it was not long before we call the police officers ... \"chickens\"!",
    "The Eiffel Tower is NOT the most visited monument in Paris. \nIn 2014, the Eiffel Tower was only the fourth most visited site in the French capital. It is the Notre-Dame de Paris cathedral that comes first.",
    "The main bell of the Notre-Dame cathedral weighs 13 tons. Or more than the weight of 3 elephants. The inner part of the bell alone weighs 500 kg. \nThe bell rings for major Catholic holidays such as Christmas, Easter, Pentecost, etc., or for other important events such as the death of Pope John Paul II and the election of his successor Benedict XVI. \nOh, and the biggest bell has a name: Emmanuel.",
    "Ghost subway stations are hiding under Paris soil. \nAnd not just one ... 14 ghost metro stations are hidden in the basement of the capital. Most of them were closed at the beginning of the Second World War, while a large part of the personnel had been mobilized for the war. \nSome are then reopened temporarily, then permanently abandoned, being too close to other stations. This is the case, for example, of the St Martin station, located 100m from Strasbourg-St Denis. \nIt is one of the largest abandoned resorts in the capital, regularly visited by urban explorers ...",
    "Place de la Concorde is one of the largest sundials in the world. \nMost Parisians themselves do not know, but the Place de la Concorde is a giant sundial. The Obelisk (the main monument of the square, an Egyptian column 23 meters high) can read the approximate time depending on its shadow, depending on the position of the sun. \nIf you pay attention while walking around the Place de la Concorde, you will even notice some markers of the hour in Roman numerals on the pavement."
  ];
};

module.exports = arrayOfAnecdote;
