module.exports = {
  'eat': [],
  'start': ['start', 'init'],
  'feedback': [],
  'trip': [],
  'itinerary': [],
  'menu': [],
  'aroundMe': [],
  'changeCity': [],
  'ticket': [],
  'visit': [],
  'go': [],
  'drink': [],
  'talkingToHuman': [],
  'back': [],
  'favorite': [],
  'subscribe': [],
  'help': [],
  'share': [],
};