module.exports = {
  'eat': ['eat'],
  'start': ['start', 'init'],
  'feedback': ['feedback'],
  'trip': ['trip'],
  'itinerary': ['itinerary'],
  'menu': ['menu'],
  'aroundMe': ['aroundMe'],
  'changeCity': ['changeCity'],
  'ticket': ['ticket'],
  'visit': ['visit'],
  'go': ['go'],
  'drink': ['drink'],
  'talkingToHuman': ['talkingToHuman'],
  'back': ['back'],
  'favorite': ['favorite'],
  'subscribe': ['subscribe'],
  'help': ['help'],
  'share': ['share'],
  'next': ['next'],
  'map': ['map'],
  'description': ['description'],
  'unknown': ['unknown']
};